apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic-hmzn
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/vigneshsri-tenant/devfile-sample-go-basic-1/devfile-sample-go-basic-hmzn@sha256:00ac910e579b4ddaf6804a66a971add881abb95f4d8aa5e091d97deb7ba1bc48
        name: my-go
        resources: {}
status: {}
